### PR TITLE
Update to readout scheme files

### PR DESCRIPTION
**Pull request by mrtommyb**
This PR includes a large update to the readout schema. it significantly complicates things but I think that is necessary.

The new files are broken into additional sections. Under data we have
- CommandName - this should be used in the target XML file in place of where we are currently using NIRDA/VDA.
- IncludedMnemonics - this is the list of readout scheme names that are included in the file
- FixedParameters - these should always be included in the science calendar XML file, with the values provided

All values that go into the science calendar XML are strings, integers, or floats. Only parameters that have decimal points in the readout files should be floats. IntegrationTime_s should not go into the XML file, but are used to calculate the number of integrations

### CODE REVIEW

**Comment by mrtommyb** [comment]
You will notice that I have added two special keywords in the files
- SET_BY_SCHEDULER
- SET_BY_TARGET_DEFINITION_FILE

SET_BY_SCHEDULER is fairly simple, its the number of integrations and the scheduler should calculate this and add it to the XML block.

SET_BY_TARGET_DEFINITION_FILE are parameters that come from the target defintion files. So for example, TargetID and TargetRA are the parameters that are directly in the target defintion files.

@benhord we do need to think about how we handle these four lines. They are all relating to the reference stars
            "StarRoiDetMethod": "SET_BY_TARGET_DEFINITION_FILE",
            "numPredefinedStarRois": "SET_BY_TARGET_DEFINITION_FILE",
            "PredefinedStarRoiRa": "SET_BY_TARGET_DEFINITION_FILE",
            "PredefinedStarRoiDec": "SET_BY_TARGET_DEFINITION_FILE",

**Comment by mrtommyb** [comment]
The full target block should be have the tag "CommandName" and then within that block have all the parameters from both "FixedParameters" and the particular readout scheme mnemonic named in the target defintion file. so here is an example for each channel

``` XML
			<Payload_Parameters>
				<AcquireInfCamImages>
					<AverageGroups>1</AverageGroups>
					<ROI_StartX>0</ROI_StartX>
					<ROI_StartY>824</ROI_StartY>
					<ROI_SizeX>80</ROI_SizeX>
					<ROI_SizeY>400</ROI_SizeY>
                                          <TargetID>TOI-836 b</TargetID>
					<SC_Resets1>1</SC_Resets1>
					<SC_Resets2>1</SC_Resets2>
					<SC_DropFrames1>0</SC_DropFrames1>
					<SC_DropFrames2>16</SC_DropFrames2>
					<SC_DropFrames3>0</SC_DropFrames3>
					<SC_ReadFrames>4</SC_ReadFrames>
					<SC_Groups>2</SC_Groups>
					<SC_Integrations>525</SC_Integrations>
				</AcquireInfCamImages>
				<AcquireVisCamScienceData>
                                         <NumExposuresMax>1</NumExposuresMax>
                                         <IncludeFieldSolnsInResp>1</IncludeFieldSolnsInResp>
					<TargetID>TOI-836 b</TargetID>
					<TargetRA>225.08082665422998</TargetRA>
					<TargetDEC>-24.45408163177</TargetDEC>
					<StarRoiDetMethod>0</StatRoiDetMethod>
					<numPredefinedStarRois>5</numPredefinedStarRois>
					<FramesPerCoadd>50</FramesPerCoadd>
					<PredefinedStarRoiRa>
                                                  <RA1>60.1</RA1>
                                                  <RA2>60.2</RA2>
                                                  <RA3>60.3</RA3>
                                                  <RA4>60.4</RA4>
                                                  <RA5>60.5</RA5>
                                         </PredefinedStarRoiRa>
					<PredefinedStarRoiDec>
                                                  <Dec1>-30.1</Dec1>
                                                  <Dec2>-30.2</Dec2>
                                                  <Dec3>-30.3</Dec3>
                                                  <Dec4>-30.4</Dec4>
                                                  <Dec5>-30.5</Dec5>
                                         </PredefinedStarRoiDec>
					<StarRoiDimension>50</StarRoiDimension>
					<MaxNumStarRois>0</MaxNumStarRois>
					<ExposureTime_us>200000</ExposureTime_us>
                                         <NumTotalFramesRequested>9000</NumTotalFramesRequested>
				</AcquireVisCamScienceData>
			</Payload_Parameters>
```

**Comment by mrtommyb** [comment]
I also updated the readme

**Comment by benhord** [comment]
I changed the code that produces the target definition files to now mesh with the new format of the readout schemes and tested it so there shouldn't be any issues creating JSON files with the new changes.

**Comment by benhord** [comment]
> You will notice that I have added two special keywords in the files
> 
> * SET_BY_SCHEDULER
> * SET_BY_TARGET_DEFINITION_FILE
> 
> SET_BY_SCHEDULER is fairly simple, its the number of integrations and the scheduler should calculate this and add it to the XML block.
> 
> SET_BY_TARGET_DEFINITION_FILE are parameters that come from the target defintion files. So for example, TargetID and TargetRA are the parameters that are directly in the target defintion files.
> 
> @benhord we do need to think about how we handle these four lines. They are all relating to the reference stars "StarRoiDetMethod": "SET_BY_TARGET_DEFINITION_FILE", "numPredefinedStarRois": "SET_BY_TARGET_DEFINITION_FILE", "PredefinedStarRoiRa": "SET_BY_TARGET_DEFINITION_FILE", "PredefinedStarRoiDec": "SET_BY_TARGET_DEFINITION_FILE",

I agree. I'm polishing the code in pandorasim that picks the best ROIs and spits out the coordinates. Once that's done, I'll integrate ROI selection into the target definition file generation workflow and regenerate all of the files. I've added an issue about it here: #10

**Review by benhord — APPROVED** [review]
The changes look good to me. I tested the workflow and everything runs smoothly.

**Comment by mrtommyb** [comment]
@vbkostov what do you think about these changes?

**Review by mrtommyb — COMMENTED** [review]
@benhord those changes look good

**Comment by mrtommyb** [comment]
Per discussion with @vbkostov on slack, he approves this merge.

**Pull request merged**
